# Generated by Django 3.2.5 on 2021-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_player_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='c_score',
        ),
        migrations.AddField(
            model_name='player',
            name='dbms_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ds_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
