# Generated by Django 3.2.5 on 2021-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211117_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DS_Question',
            new_name='DS_Questions',
        ),
    ]
