# Generated by Django 3.2.5 on 2021-11-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211117_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dbms',
        ),
        migrations.DeleteModel(
            name='Ds',
        ),
    ]
