# Generated by Django 3.2.5 on 2021-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211117_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Option1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Option2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Option3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Option4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsdbms',
            name='Question',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Option1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Option2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Option3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Option4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsds',
            name='Question',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
